// Lista completa de paises (codigo de marcado + ISO2) para los selectores de
// telefono del pre-call y la agenda. Generada una sola vez; agregar paises
// nuevos a mano esta bien, solo mantener el campo iso consistente con
// COUNTRY_DIAL_CODES en entrenamiento/api/_phone.js y src/utils/phone.js.

export type CountryPrefix = { code: string; flag: string; name: string; iso: string }

// Los mas frecuentes entre los clientes actuales, se muestran primero.
export const COMMON_COUNTRY_PREFIXES: CountryPrefix[] = [
  { code: '+598', flag: '🇺🇾', name: 'Uruguay', iso: 'UY' },
  { code: '+54', flag: '🇦🇷', name: 'Argentina', iso: 'AR' },
  { code: '+56', flag: '🇨🇱', name: 'Chile', iso: 'CL' },
  { code: '+57', flag: '🇨🇴', name: 'Colombia', iso: 'CO' },
  { code: '+52', flag: '🇲🇽', name: 'México', iso: 'MX' },
  { code: '+55', flag: '🇧🇷', name: 'Brasil', iso: 'BR' },
  { code: '+51', flag: '🇵🇪', name: 'Perú', iso: 'PE' },
  { code: '+58', flag: '🇻🇪', name: 'Venezuela', iso: 'VE' },
  { code: '+595', flag: '🇵🇾', name: 'Paraguay', iso: 'PY' },
  { code: '+591', flag: '🇧🇴', name: 'Bolivia', iso: 'BO' },
  { code: '+593', flag: '🇪🇨', name: 'Ecuador', iso: 'EC' },
  { code: '+34', flag: '🇪🇸', name: 'España', iso: 'ES' },
  { code: '+1', flag: '🇺🇸', name: 'Estados Unidos', iso: 'US' },
]

// Resto del mundo, orden alfabetico.
export const OTHER_COUNTRY_PREFIXES: CountryPrefix[] = [
  { code: '+93', flag: '🇦🇫', name: 'Afganistán', iso: 'AF' },
  { code: '+355', flag: '🇦🇱', name: 'Albania', iso: 'AL' },
  { code: '+49', flag: '🇩🇪', name: 'Alemania', iso: 'DE' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra', iso: 'AD' },
  { code: '+244', flag: '🇦🇴', name: 'Angola', iso: 'AO' },
  { code: '+1', flag: '🇦🇬', name: 'Antigua y Barbuda', iso: 'AG' },
  { code: '+966', flag: '🇸🇦', name: 'Arabia Saudita', iso: 'SA' },
  { code: '+213', flag: '🇩🇿', name: 'Argelia', iso: 'DZ' },
  { code: '+374', flag: '🇦🇲', name: 'Armenia', iso: 'AM' },
  { code: '+61', flag: '🇦🇺', name: 'Australia', iso: 'AU' },
  { code: '+43', flag: '🇦🇹', name: 'Austria', iso: 'AT' },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaiyán', iso: 'AZ' },
  { code: '+1', flag: '🇧🇸', name: 'Bahamas', iso: 'BS' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladés', iso: 'BD' },
  { code: '+1', flag: '🇧🇧', name: 'Barbados', iso: 'BB' },
  { code: '+973', flag: '🇧🇭', name: 'Baréin', iso: 'BH' },
  { code: '+32', flag: '🇧🇪', name: 'Bélgica', iso: 'BE' },
  { code: '+501', flag: '🇧🇿', name: 'Belice', iso: 'BZ' },
  { code: '+229', flag: '🇧🇯', name: 'Benín', iso: 'BJ' },
  { code: '+375', flag: '🇧🇾', name: 'Bielorrusia', iso: 'BY' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia y Herzegovina', iso: 'BA' },
  { code: '+267', flag: '🇧🇼', name: 'Botsuana', iso: 'BW' },
  { code: '+673', flag: '🇧🇳', name: 'Brunéi', iso: 'BN' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria', iso: 'BG' },
  { code: '+226', flag: '🇧🇫', name: 'Burkina Faso', iso: 'BF' },
  { code: '+975', flag: '🇧🇹', name: 'Bután', iso: 'BT' },
  { code: '+238', flag: '🇨🇻', name: 'Cabo Verde', iso: 'CV' },
  { code: '+855', flag: '🇰🇭', name: 'Camboya', iso: 'KH' },
  { code: '+237', flag: '🇨🇲', name: 'Camerún', iso: 'CM' },
  { code: '+1', flag: '🇨🇦', name: 'Canadá', iso: 'CA' },
  { code: '+974', flag: '🇶🇦', name: 'Catar', iso: 'QA' },
  { code: '+235', flag: '🇹🇩', name: 'Chad', iso: 'TD' },
  { code: '+86', flag: '🇨🇳', name: 'China', iso: 'CN' },
  { code: '+357', flag: '🇨🇾', name: 'Chipre', iso: 'CY' },
  { code: '+379', flag: '🇻🇦', name: 'Ciudad del Vaticano', iso: 'VA' },
  { code: '+269', flag: '🇰🇲', name: 'Comoras', iso: 'KM' },
  { code: '+242', flag: '🇨🇬', name: 'Congo', iso: 'CG' },
  { code: '+850', flag: '🇰🇵', name: 'Corea del Norte', iso: 'KP' },
  { code: '+82', flag: '🇰🇷', name: 'Corea del Sur', iso: 'KR' },
  { code: '+225', flag: '🇨🇮', name: 'Costa de Marfil', iso: 'CI' },
  { code: '+506', flag: '🇨🇷', name: 'Costa Rica', iso: 'CR' },
  { code: '+385', flag: '🇭🇷', name: 'Croacia', iso: 'HR' },
  { code: '+53', flag: '🇨🇺', name: 'Cuba', iso: 'CU' },
  { code: '+45', flag: '🇩🇰', name: 'Dinamarca', iso: 'DK' },
  { code: '+1', flag: '🇩🇲', name: 'Dominica', iso: 'DM' },
  { code: '+20', flag: '🇪🇬', name: 'Egipto', iso: 'EG' },
  { code: '+503', flag: '🇸🇻', name: 'El Salvador', iso: 'SV' },
  { code: '+971', flag: '🇦🇪', name: 'Emiratos Árabes Unidos', iso: 'AE' },
  { code: '+291', flag: '🇪🇷', name: 'Eritrea', iso: 'ER' },
  { code: '+421', flag: '🇸🇰', name: 'Eslovaquia', iso: 'SK' },
  { code: '+386', flag: '🇸🇮', name: 'Eslovenia', iso: 'SI' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia', iso: 'EE' },
  { code: '+268', flag: '🇸🇿', name: 'Esuatini', iso: 'SZ' },
  { code: '+251', flag: '🇪🇹', name: 'Etiopía', iso: 'ET' },
  { code: '+63', flag: '🇵🇭', name: 'Filipinas', iso: 'PH' },
  { code: '+358', flag: '🇫🇮', name: 'Finlandia', iso: 'FI' },
  { code: '+679', flag: '🇫🇯', name: 'Fiyi', iso: 'FJ' },
  { code: '+33', flag: '🇫🇷', name: 'Francia', iso: 'FR' },
  { code: '+241', flag: '🇬🇦', name: 'Gabón', iso: 'GA' },
  { code: '+220', flag: '🇬🇲', name: 'Gambia', iso: 'GM' },
  { code: '+995', flag: '🇬🇪', name: 'Georgia', iso: 'GE' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana', iso: 'GH' },
  { code: '+1', flag: '🇬🇩', name: 'Granada', iso: 'GD' },
  { code: '+30', flag: '🇬🇷', name: 'Grecia', iso: 'GR' },
  { code: '+502', flag: '🇬🇹', name: 'Guatemala', iso: 'GT' },
  { code: '+594', flag: '🇬🇫', name: 'Guayana Francesa', iso: 'GF' },
  { code: '+224', flag: '🇬🇳', name: 'Guinea', iso: 'GN' },
  { code: '+240', flag: '🇬🇶', name: 'Guinea Ecuatorial', iso: 'GQ' },
  { code: '+245', flag: '🇬🇼', name: 'Guinea-Bisáu', iso: 'GW' },
  { code: '+592', flag: '🇬🇾', name: 'Guyana', iso: 'GY' },
  { code: '+509', flag: '🇭🇹', name: 'Haití', iso: 'HT' },
  { code: '+504', flag: '🇭🇳', name: 'Honduras', iso: 'HN' },
  { code: '+852', flag: '🇭🇰', name: 'Hong Kong', iso: 'HK' },
  { code: '+36', flag: '🇭🇺', name: 'Hungría', iso: 'HU' },
  { code: '+91', flag: '🇮🇳', name: 'India', iso: 'IN' },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia', iso: 'ID' },
  { code: '+964', flag: '🇮🇶', name: 'Irak', iso: 'IQ' },
  { code: '+98', flag: '🇮🇷', name: 'Irán', iso: 'IR' },
  { code: '+353', flag: '🇮🇪', name: 'Irlanda', iso: 'IE' },
  { code: '+354', flag: '🇮🇸', name: 'Islandia', iso: 'IS' },
  { code: '+692', flag: '🇲🇭', name: 'Islas Marshall', iso: 'MH' },
  { code: '+677', flag: '🇸🇧', name: 'Islas Salomón', iso: 'SB' },
  { code: '+972', flag: '🇮🇱', name: 'Israel', iso: 'IL' },
  { code: '+39', flag: '🇮🇹', name: 'Italia', iso: 'IT' },
  { code: '+1', flag: '🇯🇲', name: 'Jamaica', iso: 'JM' },
  { code: '+81', flag: '🇯🇵', name: 'Japón', iso: 'JP' },
  { code: '+962', flag: '🇯🇴', name: 'Jordania', iso: 'JO' },
  { code: '+7', flag: '🇰🇿', name: 'Kazajistán', iso: 'KZ' },
  { code: '+254', flag: '🇰🇪', name: 'Kenia', iso: 'KE' },
  { code: '+996', flag: '🇰🇬', name: 'Kirguistán', iso: 'KG' },
  { code: '+686', flag: '🇰🇮', name: 'Kiribati', iso: 'KI' },
  { code: '+383', flag: '🇽🇰', name: 'Kosovo', iso: 'XK' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait', iso: 'KW' },
  { code: '+856', flag: '🇱🇦', name: 'Laos', iso: 'LA' },
  { code: '+266', flag: '🇱🇸', name: 'Lesoto', iso: 'LS' },
  { code: '+371', flag: '🇱🇻', name: 'Letonia', iso: 'LV' },
  { code: '+961', flag: '🇱🇧', name: 'Líbano', iso: 'LB' },
  { code: '+231', flag: '🇱🇷', name: 'Liberia', iso: 'LR' },
  { code: '+218', flag: '🇱🇾', name: 'Libia', iso: 'LY' },
  { code: '+423', flag: '🇱🇮', name: 'Liechtenstein', iso: 'LI' },
  { code: '+370', flag: '🇱🇹', name: 'Lituania', iso: 'LT' },
  { code: '+352', flag: '🇱🇺', name: 'Luxemburgo', iso: 'LU' },
  { code: '+853', flag: '🇲🇴', name: 'Macao', iso: 'MO' },
  { code: '+389', flag: '🇲🇰', name: 'Macedonia del Norte', iso: 'MK' },
  { code: '+261', flag: '🇲🇬', name: 'Madagascar', iso: 'MG' },
  { code: '+60', flag: '🇲🇾', name: 'Malasia', iso: 'MY' },
  { code: '+265', flag: '🇲🇼', name: 'Malaui', iso: 'MW' },
  { code: '+960', flag: '🇲🇻', name: 'Maldivas', iso: 'MV' },
  { code: '+223', flag: '🇲🇱', name: 'Malí', iso: 'ML' },
  { code: '+356', flag: '🇲🇹', name: 'Malta', iso: 'MT' },
  { code: '+212', flag: '🇲🇦', name: 'Marruecos', iso: 'MA' },
  { code: '+230', flag: '🇲🇺', name: 'Mauricio', iso: 'MU' },
  { code: '+691', flag: '🇫🇲', name: 'Micronesia', iso: 'FM' },
  { code: '+373', flag: '🇲🇩', name: 'Moldavia', iso: 'MD' },
  { code: '+377', flag: '🇲🇨', name: 'Mónaco', iso: 'MC' },
  { code: '+976', flag: '🇲🇳', name: 'Mongolia', iso: 'MN' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro', iso: 'ME' },
  { code: '+258', flag: '🇲🇿', name: 'Mozambique', iso: 'MZ' },
  { code: '+95', flag: '🇲🇲', name: 'Myanmar', iso: 'MM' },
  { code: '+264', flag: '🇳🇦', name: 'Namibia', iso: 'NA' },
  { code: '+674', flag: '🇳🇷', name: 'Nauru', iso: 'NR' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal', iso: 'NP' },
  { code: '+505', flag: '🇳🇮', name: 'Nicaragua', iso: 'NI' },
  { code: '+227', flag: '🇳🇪', name: 'Níger', iso: 'NE' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria', iso: 'NG' },
  { code: '+47', flag: '🇳🇴', name: 'Noruega', iso: 'NO' },
  { code: '+64', flag: '🇳🇿', name: 'Nueva Zelanda', iso: 'NZ' },
  { code: '+968', flag: '🇴🇲', name: 'Omán', iso: 'OM' },
  { code: '+31', flag: '🇳🇱', name: 'Países Bajos', iso: 'NL' },
  { code: '+92', flag: '🇵🇰', name: 'Pakistán', iso: 'PK' },
  { code: '+680', flag: '🇵🇼', name: 'Palaos', iso: 'PW' },
  { code: '+970', flag: '🇵🇸', name: 'Palestina', iso: 'PS' },
  { code: '+507', flag: '🇵🇦', name: 'Panamá', iso: 'PA' },
  { code: '+675', flag: '🇵🇬', name: 'Papúa Nueva Guinea', iso: 'PG' },
  { code: '+48', flag: '🇵🇱', name: 'Polonia', iso: 'PL' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal', iso: 'PT' },
  { code: '+1', flag: '🇵🇷', name: 'Puerto Rico', iso: 'PR' },
  { code: '+44', flag: '🇬🇧', name: 'Reino Unido', iso: 'GB' },
  { code: '+236', flag: '🇨🇫', name: 'Rep. Centroafricana', iso: 'CF' },
  { code: '+243', flag: '🇨🇩', name: 'Rep. Dem. del Congo', iso: 'CD' },
  { code: '+420', flag: '🇨🇿', name: 'República Checa', iso: 'CZ' },
  { code: '+1', flag: '🇩🇴', name: 'República Dominicana', iso: 'DO' },
  { code: '+250', flag: '🇷🇼', name: 'Ruanda', iso: 'RW' },
  { code: '+40', flag: '🇷🇴', name: 'Rumania', iso: 'RO' },
  { code: '+7', flag: '🇷🇺', name: 'Rusia', iso: 'RU' },
  { code: '+685', flag: '🇼🇸', name: 'Samoa', iso: 'WS' },
  { code: '+1', flag: '🇰🇳', name: 'San Cristóbal y Nieves', iso: 'KN' },
  { code: '+378', flag: '🇸🇲', name: 'San Marino', iso: 'SM' },
  { code: '+1', flag: '🇻🇨', name: 'San Vicente y las Granadinas', iso: 'VC' },
  { code: '+1', flag: '🇱🇨', name: 'Santa Lucía', iso: 'LC' },
  { code: '+221', flag: '🇸🇳', name: 'Senegal', iso: 'SN' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia', iso: 'RS' },
  { code: '+248', flag: '🇸🇨', name: 'Seychelles', iso: 'SC' },
  { code: '+232', flag: '🇸🇱', name: 'Sierra Leona', iso: 'SL' },
  { code: '+65', flag: '🇸🇬', name: 'Singapur', iso: 'SG' },
  { code: '+963', flag: '🇸🇾', name: 'Siria', iso: 'SY' },
  { code: '+252', flag: '🇸🇴', name: 'Somalia', iso: 'SO' },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', iso: 'LK' },
  { code: '+27', flag: '🇿🇦', name: 'Sudáfrica', iso: 'ZA' },
  { code: '+249', flag: '🇸🇩', name: 'Sudán', iso: 'SD' },
  { code: '+211', flag: '🇸🇸', name: 'Sudán del Sur', iso: 'SS' },
  { code: '+46', flag: '🇸🇪', name: 'Suecia', iso: 'SE' },
  { code: '+41', flag: '🇨🇭', name: 'Suiza', iso: 'CH' },
  { code: '+597', flag: '🇸🇷', name: 'Surinam', iso: 'SR' },
  { code: '+66', flag: '🇹🇭', name: 'Tailandia', iso: 'TH' },
  { code: '+886', flag: '🇹🇼', name: 'Taiwán', iso: 'TW' },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania', iso: 'TZ' },
  { code: '+992', flag: '🇹🇯', name: 'Tayikistán', iso: 'TJ' },
  { code: '+670', flag: '🇹🇱', name: 'Timor Oriental', iso: 'TL' },
  { code: '+228', flag: '🇹🇬', name: 'Togo', iso: 'TG' },
  { code: '+676', flag: '🇹🇴', name: 'Tonga', iso: 'TO' },
  { code: '+1', flag: '🇹🇹', name: 'Trinidad y Tobago', iso: 'TT' },
  { code: '+216', flag: '🇹🇳', name: 'Túnez', iso: 'TN' },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistán', iso: 'TM' },
  { code: '+90', flag: '🇹🇷', name: 'Turquía', iso: 'TR' },
  { code: '+688', flag: '🇹🇻', name: 'Tuvalu', iso: 'TV' },
  { code: '+380', flag: '🇺🇦', name: 'Ucrania', iso: 'UA' },
  { code: '+256', flag: '🇺🇬', name: 'Uganda', iso: 'UG' },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistán', iso: 'UZ' },
  { code: '+678', flag: '🇻🇺', name: 'Vanuatu', iso: 'VU' },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam', iso: 'VN' },
  { code: '+967', flag: '🇾🇪', name: 'Yemen', iso: 'YE' },
  { code: '+253', flag: '🇩🇯', name: 'Yibuti', iso: 'DJ' },
  { code: '+260', flag: '🇿🇲', name: 'Zambia', iso: 'ZM' },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabue', iso: 'ZW' },
]

export const COUNTRY_PREFIXES: CountryPrefix[] = [...COMMON_COUNTRY_PREFIXES, ...OTHER_COUNTRY_PREFIXES]

export const PREFIX_TO_ISO: Record<string, string> = Object.fromEntries(
  COUNTRY_PREFIXES.map(p => [p.code, p.iso])
)
